// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifogyudjxbeazexskzjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmb2d5dWRqeGJlYXpleHNrempmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjAxNzIsImV4cCI6MjA2MDgzNjE3Mn0.XjvLqqYCEBz3JLY_cSDaYI1_ThNG5_BhNc1lJpjXPbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);